##  Excercises



 1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np


2. Print the numpy version and the configuration

In [2]:
import numpy as np

print("NumPy Version:", np.__version__)
print("\nNumPy Configuration:")
print(np.show_config())


NumPy Version: 1.26.4

NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30153",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITIN

C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Create a null vector of size 10

In [3]:
import numpy as np

null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [6]:
import numpy as np

# Create an example array
arr = np.zeros((3, 4))

# Find the memory size in bytes
memory_size = arr.nbytes

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 96 bytes


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
pydoc numpy.add


6. Create a null vector of size 10 but the fifth value which is 1 

In [5]:
import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1  # Indexing starts from 0, so the fifth value has index 4
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [6]:
import numpy as np

vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [7]:
import numpy as np

# Create an example vector
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector
reversed_vector = np.flip(vector)

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)


Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
0 1 2
3 4 5
6 7 8


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:

The indices of the non-zero elements in the array [1, 2, 0, 0, 4, 0] are:

1 (index 0)
2 (index 1)
4 (index 4)

So, the indices are [0, 1, 4].

11. An identity matrix is a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros. Here's a 3x3 identity matrix:

In [ ]:
1 0 0
0 1 0
0 0 1


12. Create a 3x3x3 array with random values

In [9]:
import numpy as np

# Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)

print(array)


[[[0.37470863 0.64274376 0.89634793]
  [0.95375535 0.86295522 0.35059506]
  [0.01840845 0.35694524 0.19693194]]

 [[0.49678368 0.85324568 0.13136191]
  [0.36304732 0.80009065 0.22041817]
  [0.00592681 0.10950173 0.77017731]]

 [[0.00648927 0.31218225 0.22991855]
  [0.56381713 0.06905077 0.35000862]
  [0.58355258 0.57403203 0.44916165]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [10]:
import numpy as np

# Create a 10x10 array with random values
array = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.010738816564993314
Maximum value: 0.9902782768880924


14. Create a random vector of size 30 and find the mean value

In [11]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Calculate the mean value of the elements in the vector
mean_value = np.mean(random_vector)

print("Mean value:", mean_value)


Mean value: 0.45981970581381865


15. Create a 2d array with 1 on the border and 0 inside

In [12]:
import numpy as np

# Define the dimensions of the array
rows = 5
cols = 5

# Create an empty array filled with zeros
array = np.zeros((rows, cols), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top row
array[:, 0] = 1  # Leftmost column
array[-1, :] = 1  # Bottom row
array[:, -1] = 1  # Rightmost column

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array?

In [13]:
import numpy as np

# Example existing array
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Determine the dimensions of the new array with the border
new_rows = existing_array.shape[0] + 2  # Add 2 for the top and bottom borders
new_cols = existing_array.shape[1] + 2  # Add 2 for the left and right borders

# Create a new array filled with zeros
new_array = np.zeros((new_rows, new_cols), dtype=existing_array.dtype)

# Place the existing array in the center of the new array
new_array[1:-1, 1:-1] = existing_array

print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(new_array)


Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [ ]:
0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False

You can achieve this by creating a 5x5 matrix filled with zeros and then setting the values just below the diagonal to 1, 2, 3, 4. Here's how you can do it:

In [14]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5), dtype=int)

# Set values 1, 2, 3, 4 just below the diagonal
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [15]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8), dtype=int)

# Fill the even rows and columns with 1
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
import numpy as np

# Define the shape of the array
shape = (6, 7, 8)

# Total number of elements
total_elements = np.prod(shape)

# Find the index (x, y, z) of the 100th element
index_1d = 99  # Since Python indexing starts from 0, the 100th element has index 99
index_3d = np.unravel_index(index_1d, shape)

print("Index (x, y, z) of the 100th element:", index_3d)


Index (x, y, z) of the 100th element: (1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function

In [17]:
import numpy as np

# Define the checkerboard pattern
checkerboard_pattern = np.array([[0, 1], [1, 0]])

# Use np.tile to repeat the pattern to create an 8x8 matrix
checkerboard = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix 

In [18]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.21797289 0.6508912  0.36458192 0.96514361 0.122472  ]
 [0.89536369 0.69987527 0.00541703 0.59548987 0.35271127]
 [0.05294868 0.0415435  0.03573548 0.44902977 0.86675035]
 [0.61970048 0.53152124 0.26441185 0.79512052 0.88629294]
 [0.47271481 0.5474783  0.77079445 0.7135371  0.14318921]]

Normalized Matrix:
[[-0.87906448  0.55998442 -0.39172643  1.60458008 -1.19651571]
 [ 1.37262704  0.72281069 -1.58561413  0.37582675 -0.43118526]
 [-1.42761583 -1.46552739 -1.48483363 -0.11101624  1.27751441]
 [ 0.45630442  0.16319081 -0.72469833  1.03941215  1.34247528]
 [-0.03228561  0.21623314  0.95855069  0.76822352 -1.12765036]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)


In [19]:
import numpy as np

# Define the custom dtype for RGBA color
rgba_dtype = np.dtype([('R', np.uint8),   # Red component
                       ('G', np.uint8),   # Green component
                       ('B', np.uint8),   # Blue component
                       ('A', np.uint8)])  # Alpha component

print("Custom RGBA dtype:")
print(rgba_dtype)


Custom RGBA dtype:
[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [20]:
import numpy as np

# Create a 5x3 matrix
matrix1 = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix2 = np.random.rand(3, 2)

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)  # or equivalently, matrix1 @ matrix2

print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[0.27486479 0.18563832]
 [0.82527005 0.75903414]
 [1.28077513 1.00636163]
 [0.53926332 0.37220524]
 [0.80385999 0.47085905]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [21]:
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Negate elements between 3 and 8
array[3:9] *= -1

print("Result:", array)


Result: [ 1  2  3 -4 -5 -6 -7 -8 -9 10]


26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
9
10


User
27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
// the legal expressions are:

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
The illegal expression is:

Z<Z>Z







28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [ ]:
So, the results of the expressions are:

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): nan
np.array([np.nan]).astype(int).astype(float): [0.]

29. How to round away from zero a float array ?

In [23]:
import numpy as np

# Example float array
float_array = np.array([-1.5, 2.3, -3.7, 4.5])

# Round away from zero
rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))

print("Original array:", float_array)
print("Rounded away from zero array:", rounded_array)


Original array: [-1.5  2.3 -3.7  4.5]
Rounded away from zero array: [-2.  3. -4.  5.]


30. How to find common values between two arrays? (★☆☆)


In [24]:
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)



Common values: [3 4 5]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [25]:
import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)


32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
#No, the expression is not true.

#NumPy's np.sqrt(-1) returns a runtime warning (RuntimeWarning: invalid value encountered in sqrt) 
#because it attempts to take the square root of a negative number, which is not a real number. Therefore, the result of np.sqrt(-1) is nan (not a number).

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [26]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-07
Today: 2024-02-08
Tomorrow: 2024-02-09


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [27]:
import calendar

def get_dates_july_2016():
    # Get the number of days in July 2016
    num_days = calendar.monthrange(2016, 7)[1]

    # Generate dates for July 2016
    dates = [f"2016-07-{str(day).zfill(2)}" for day in range(1, num_days + 1)]

    return dates

# Test the function
dates_july_2016 = get_dates_july_2016()
print(dates_july_2016)


['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04', '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08', '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12', '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16', '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20', '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24', '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28', '2016-07-29', '2016-07-30', '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np

def compute_in_place(A, B):
    A += B  # Modify A in place by adding B
    A *= -A/2  # Modify A in place by multiplying by -A/2

# Example usage:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

compute_in_place(A, B)

print(A)  # Output the result of ((A+B)*(-A/2))


36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [29]:
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Generating numbers between 0 and 10

# Method 1: Using astype method
integer_part_1 = random_array.astype(int)

# Method 2: Using floor function
integer_part_2 = np.floor(random_array)

# Method 3: Using integer division followed by multiplication
integer_part_3 = (random_array // 1).astype(int)

# Method 4: Using trunc function
integer_part_4 = np.trunc(random_array).astype(int)

print("Original Array:", random_array)
print("Integer part (Method 1):", integer_part_1)
print("Integer part (Method 2):", integer_part_2)
print("Integer part (Method 3):", integer_part_3)
print("Integer part (Method 4):", integer_part_4)


Original Array: [7.11736064 7.55789527 0.18604182 9.32619261 2.92098542]
Integer part (Method 1): [7 7 0 9 2]
Integer part (Method 2): [7. 7. 0. 9. 2.]
Integer part (Method 3): [7 7 0 9 2]
Integer part (Method 4): [7 7 0 9 2]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [30]:
import numpy as np

# Create a 1D array ranging from 0 to 4
row_values = np.arange(5)

# Use broadcasting to create the 5x5 matrix
matrix = np.tile(row_values, (5, 1))

print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [31]:
import numpy as np

# Define the generator function
def generate_integers():
    for i in range(10):
        yield i

# Use the generator function to build an array
array_from_generator = np.fromiter(generate_integers(), dtype=int)

print(array_from_generator)


[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [32]:
import numpy as np

# Create a vector of size 10 with values ranging from 0 to 1 (both excluded)
vector = np.linspace(0, 1, 12, endpoint=False)[1:-1]

print(vector)


[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the random vector
sorted_vector = np.sort(random_vector)

print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


Random Vector: [0.19695886 0.5080267  0.17802855 0.71808242 0.55912696 0.41246088
 0.74245844 0.96650049 0.46373465 0.7233828 ]
Sorted Vector: [0.17802855 0.19695886 0.41246088 0.46373465 0.5080267  0.55912696
 0.71808242 0.7233828  0.74245844 0.96650049]


41. How to sum a small array faster than np.sum? (★★☆)


In [34]:
import numpy as np

# Define a small array
small_array = np.array([1, 2, 3, 4, 5])

# Sum the small array using np.sum
sum_np = np.sum(small_array)

# Sum the small array using the built-in sum function
sum_builtin = sum(small_array)

print("Sum using np.sum:", sum_np)
print("Sum using built-in sum function:", sum_builtin)


Sum using np.sum: 15
Sum using built-in sum function: 15


42. Consider two random array A and B, check if they are equal (★★☆)

In [35]:
import numpy as np

# Generate random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are arrays A and B equal?", are_equal)


Array A: [0.71960833 0.70029731 0.0666741  0.5541978  0.26424605]
Array B: [0.25593324 0.84915542 0.69033575 0.75260742 0.66657497]
Are arrays A and B equal? False


43. Make an array immutable (read-only) (★★☆)

In [36]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable
my_array.flags.writeable = False

# Try to modify the array (this will raise an error)
try:
    my_array[0] = 10
except ValueError as e:
    print("Error:", e)


Error: assignment destination is read-only


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [37]:
import numpy as np

# Generate random cartesian coordinates (10x2 matrix)
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert cartesian coordinates to polar coordinates
r = np.sqrt(x**2 + y**2)  # Compute radius
theta = np.arctan2(y, x)  # Compute angle (in radians)

# Convert angle to degrees
theta_degrees = np.degrees(theta)

# Combine radius and angle to get polar coordinates
polar_coordinates = np.column_stack((r, theta_degrees))

print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(polar_coordinates)


Cartesian Coordinates:
[[0.7646223  0.62061634]
 [0.94098682 0.23381648]
 [0.06281167 0.04387085]
 [0.36957174 0.08584005]
 [0.58527885 0.8033492 ]
 [0.61477583 0.32981731]
 [0.05237981 0.38409672]
 [0.05483579 0.01440031]
 [0.28562613 0.80026486]
 [0.5992205  0.49339243]]

Polar Coordinates:
[[9.84790284e-01 3.90649924e+01]
 [9.69601122e-01 1.39542521e+01]
 [7.66156499e-02 3.49323986e+01]
 [3.79409782e-01 1.30761746e+01]
 [9.93942284e-01 5.39248469e+01]
 [6.97659504e-01 2.82128398e+01]
 [3.87651822e-01 8.22343965e+01]
 [5.66950853e-02 1.47140889e+01]
 [8.49709441e-01 7.03577807e+01]
 [7.76209573e-01 3.94677151e+01]]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [38]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced by 0:")
print(random_vector)


Random Vector with Maximum Value Replaced by 0:
[0.06074258 0.56724974 0.53211445 0.81723521 0.8127571  0.79379437
 0.12177942 0.38671997 0.31046757 0.        ]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np

# Define the number of points in each dimension
num_points = 5  # You can adjust this as needed

# Create a structured array with x and y coordinates
structured_array = np.zeros(num_points*num_points, dtype=[('x', float), ('y', float)])

# Fill in the x and y coordinates
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, num_points), np.linspace(0, 1, num_points))

print(structured_array)


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [40]:
import numpy as np

# Define arrays X and Y
X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix C:")
print(C)


Cauchy Matrix C:
[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48. Print the minimum and maximum representable value for each numpy scalar type 

In [42]:
import numpy as np

# Integer types
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__:6}: min={info.min}, max={info.max}")

# Unsigned integer types
print("\nUnsigned integer types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__:6}: min={info.min}, max={info.max}")




Integer types:
int8  : min=-128, max=127
int16 : min=-32768, max=32767
int32 : min=-2147483648, max=2147483647
int64 : min=-9223372036854775808, max=9223372036854775807

Unsigned integer types:
uint8 : min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615


49. How to print all the values of an array? (★★☆)

In [43]:
import numpy as np

# Create a NumPy array
array = np.arange(25).reshape(5, 5)

# Adjust NumPy printing options to display the entire array
np.set_printoptions(threshold=np.inf)

# Print the entire array
print(array)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


50. How to find the closest value (to a given scalar) in a vector? 

In [45]:
import numpy as np

# Define your vector
vector = np.array([1, 3, 5, 7, 9])

# Given scalar
scalar = 6

# Find index of closest value
index = np.abs(vector - scalar).argmin()

# Retrieve closest value
closest_value = vector[index]

print("Closest value to", scalar, "in the vector is:", closest_value)


Closest value to 6 in the vector is: 5


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np

# Define the dtype for the structured array
dtype = [('position', [('x', float), ('y', float)]),
         ('color', [('r', int), ('g', int), ('b', int)])]

# Create an empty structured array with the defined dtype
structured_array = np.empty(1, dtype=dtype)

# Assign values to the structured array
structured_array['position']['x'] = 10.0
structured_array['position']['y'] = 20.0
structured_array['color']['r'] = 255
structured_array['color']['g'] = 0
structured_array['color']['b'] = 0

print(structured_array)


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [46]:
import numpy as np

# Generate random vector with shape (100, 2) representing coordinates
random_vector = np.random.rand(100, 2)

# Calculate the pairwise Euclidean distances between all points
distances = np.sqrt(np.sum((random_vector[:, np.newaxis, :] - random_vector[np.newaxis, :, :]) ** 2, axis=-1))

print(distances)


[[0.         0.58197943 0.2191109  0.33027779 0.42693915 0.57402504
  0.36110443 0.32211422 0.31396545 0.53868493 0.60740015 0.46381249
  0.47834692 0.09209082 0.47843914 0.26016929 0.23735515 0.52583187
  0.38335116 0.14337787 0.21110003 0.57913241 0.40283617 0.42078131
  0.62830886 0.57402378 0.305661   0.51486798 0.51332335 0.22528811
  0.33351213 0.17314846 0.25389969 0.50848899 0.39310565 0.59319769
  0.43345348 0.3718934  0.29450246 0.46770434 0.38251076 0.26426468
  0.46670553 0.18755242 0.45853248 0.18173541 0.53536304 0.16537762
  0.2075269  0.09074283 0.53714814 0.4429154  0.21561057 0.44548956
  0.31024389 0.20232218 0.19783981 0.41439256 0.44092868 0.33302029
  0.34369133 0.23184005 0.40106517 0.31764006 0.18190834 0.32157812
  0.37803475 0.36362057 0.15685127 0.56975886 0.60058317 0.2028228
  0.19059625 0.52161828 0.38777248 0.47573827 0.49293109 0.09191859
  0.4021448  0.27378528 0.03624437 0.3616909  0.15418716 0.08448947
  0.34665029 0.45152251 0.34131553 0.40124048 0.4

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [47]:
import numpy as np

# Create a float (32 bits) array
float_array = np.array([1.5, 2.5, 3.5, 4.5], dtype=np.float32)

# Convert float array to integer array in place
float_array.view(dtype=np.int32)[:] = float_array.view(dtype=np.int32)

print(float_array)


[1.5 2.5 3.5 4.5]


54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [ ]:
import csv

# Define the file path
file_path = "your_file_path_here.txt"  # Replace "your_file_path_here.txt" with the actual file path

# Initialize an empty list to store the data
data = []

# Open the file and read its contents using csv.reader
with open(file_path, 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        # Convert empty strings to None and convert strings to integers
        row = [int(cell.strip()) if cell.strip() else None for cell in row]
        data.append(row)

# Print the data
for row in data:
    print(row)


55. What is the equivalent of enumerate for numpy arrays? (★★☆)


In [49]:
import numpy as np

# Create a NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Iterate over the array using numpy.ndenumerate
for index, value in np.ndenumerate(arr):
    print("Index:", index, "Value:", value)


Index: (0, 0) Value: 1
Index: (0, 1) Value: 2
Index: (0, 2) Value: 3
Index: (1, 0) Value: 4
Index: (1, 1) Value: 5
Index: (1, 2) Value: 6
Index: (2, 0) Value: 7
Index: (2, 1) Value: 8
Index: (2, 2) Value: 9


56. Generate a generic 2D Gaussian-like array

In [ ]:
import numpy as np

def gaussian_2d(shape, sigma=1):
    """
    Generate a 2D Gaussian-like array.

    Parameters:
        shape (tuple): Shape of the array (rows, columns).
        sigma (float): Standard deviation of the Gaussian distribution.

    Returns:
        numpy.ndarray: 2D Gaussian-like array.
    """
    # Create a grid of coordinates
    x = np.linspace(-1, 1, shape[1])
    y = np.linspace(-1, 1, shape[0])
    x_grid, y_grid = np.meshgrid(x, y)

    # Calculate the Gaussian-like values
    gaussian_values = np.exp(-(x_grid**2 + y_grid**2) / (2 * sigma**2))

    return gaussian_values

# Example usage:
shape = (5, 5)  # Shape of the array
sigma = 1.0     # Standard deviation
gaussian_array = gaussian_2d(shape, sigma)

print(gaussian_array)


57. How to randomly place p elements in a 2D array? 

In [ ]:
import numpy as np

def randomly_place_elements(array, p):
    ""
    
    if p > total_elements:
        raise ValueError("Number of elements to place (p) cannot exceed total number of elements in the array.")
    
    # Generate random indices
    indices = np.random.choice(total_elements, p, replace=False)
    
    # Assign elements to random indices
    array_flat = array.flatten()
    array_flat[indices] = 1  # Assuming the elements to be placed are 1, you can change this value as needed
    
    # Reshape the modified flattened array to the original shape
    modified_array = array_flat.reshape((rows, cols))
    
    return modified_arra
# Example usage:
# Create a 5x5 array
array = np.zeros((5, 5))

# Place 5 elements randomly
p = 5
array_with_elements = randomly_place_elements(array, p)

print("Array with randomly placed elements:")
print(array_with_elements)


58. Subtract the mean of each row of a matrix 

In [51]:
import numpy as np

def subtract_row_mean(matrix):
    """
    Subtract the mean of each row from the corresponding row of the matrix.

    Parameters:
        matrix (numpy.ndarray): Input matrix.

    Returns:
        numpy.ndarray: Matrix with row means subtracted.
    """
    # Calculate the mean of each row
    row_means = np.mean(matrix, axis=1, keepdims=True)
    
    # Subtract the row means from the matrix
    matrix_minus_mean = matrix - row_means
    
    return matrix_minus_mean

# Example usage:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

result = subtract_row_mean(matrix)
print("Matrix with row means subtracted:")
print(result)


Matrix with row means subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column? (★★☆)

In [53]:
import numpy as np

def sort_by_nth_column(array, n):
    """
    Sort a NumPy array by the nth column.

    Parameters:
        array (numpy.ndarray): Input array.
        n (int): Index of the column to sort by.

    Returns:
        numpy.ndarray: Sorted array.
    """
    # Get indices that would sort the array by the nth column
    indices = np.argsort(array[:, n])
    
    # Use the sorted indices to rearrange the rows of the array
    sorted_array = array[indices]
    
    return sorted_array

# Example usage:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

n = 1  # Sort by the second column (indexing starts from 0)
sorted_array = sort_by_nth_column(array, n)

print("Sorted array by the nth column:")
print(sorted_array)


Sorted array by the nth column:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


60. How to tell if a given 2D array has null columns?

In [54]:
import numpy as np

def has_null_columns(array):
    """
    Check if a given 2D array has null columns (containing only zeros or NaN values).

    Parameters:
        array (numpy.ndarray): Input 2D array.

    Returns:
        bool: True if the array has null columns, False otherwise.
    """
    # Check if any column contains only zeros or NaN values
    null_columns = np.any(np.isnan(array), axis=0) | np.all(array == 0, axis=0)
    
    return np.any(null_columns)

# Example usage:
array_with_null_columns = np.array([[0, 1, 2],
                                    [0, 0, 0],
                                    [np.nan, 3, 4]])

if has_null_columns(array_with_null_columns):
    print("The array has null columns.")
else:
    print("The array does not have null columns.")


The array has null columns.


61. Find the nearest value from a given value in an array

In [55]:
import numpy as np

def find_nearest_value(array, value):
    """
    Find the nearest value from a given value in an array.

    Parameters:
        array (numpy.ndarray): Input array.
        value: Value to find the nearest value to.

    Returns:
        float: Nearest value in the array.
    """
    # Find the index of the nearest value
    index = np.abs(array - value).argmin()
    
    # Get the nearest value
    nearest_value = array[index]
    
    return nearest_value

# Example usage:
array = np.array([1, 3, 5, 7, 9])
value = 6

nearest_value = find_nearest_value(array, value)
print("Nearest value to", value, "in the array is:", nearest_value)


Nearest value to 6 in the array is: 5



62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
import numpy as np

# Create two arrays with shapes (1,3) and (3,1)
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4],
                   [5],
                   [6]])

# Initialize the sum
sum_result = 0

# Create an iterator for array1 and array2
iterator1 = np.nditer(array1)
iterator2 = np.nditer(array2)

# Iterate over the arrays and compute the sum
while not (iterator1.finished and iterator2.finished):
    sum_result += iterator1[0] + iterator2[0]
    iterator1.iternext()
    iterator2.iternext()

print("Sum of the two arrays:", sum_result)


63. Create an array class that has a name attribute (★★☆)

In [56]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, array, name=None):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)

# Example usage:
data = np.array([1, 2, 3, 4, 5])
named_array = NamedArray(data, name="MyArray")

print("Named Array:", named_array)
print("Name of the array:", named_array.name)


Named Array: [1 2 3 4 5]
Name of the array: MyArray


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [57]:
import numpy as np

def add_one_to_indexed_elements(vector, indices):
    """
    Add 1 to each element of a vector indexed by a second vector, handling repeated indices.

    Parameters:
        vector (numpy.ndarray): Input vector.
        indices (numpy.ndarray): Indices vector.

    Returns:
        numpy.ndarray: Result vector with 1 added to elements indexed by indices.
    """
    # Create a copy of the original vector to avoid modifying it in place
    result = vector.copy()
    
    # Find unique indices and their counts
    unique_indices, counts = np.unique(indices, return_counts=True)
    
    # Add 1 to elements indexed by unique indices
    result[unique_indices] += 1
    
    # Subtract the count of repeated indices from the elements indexed by those indices
    result[unique_indices] -= counts - 1
    
    return result

# Example usage:
vector = np.array([0, 1, 2, 3, 4, 5])
indices = np.array([0, 1, 2, 2, 3, 3, 4])

result = add_one_to_indexed_elements(vector, indices)
print("Result vector with 1 added to elements indexed by second vector:")
print(result)


Result vector with 1 added to elements indexed by second vector:
[1 2 2 3 5 5]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [58]:
import numpy as np

def accumulate_elements(X, I, F):
    """
    Accumulate elements of a vector X to an array F based on an index list I.

    Parameters:
        X (numpy.ndarray): Input vector.
        I (numpy.ndarray): Index list.
        F (numpy.ndarray): Array to accumulate elements into.

    Returns:
        numpy.ndarray: Accumulated array F.
    """
    np.add.at(F, I, X)
    return F

# Example usage:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 2, 3])
F = np.zeros(4)

result = accumulate_elements(X, I, F)
print("Accumulated array F:", result)


Accumulated array F: [1. 2. 7. 5.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [59]:
import numpy as np

def count_unique_colors(image):
    """
    Compute the number of unique colors in an image.

    Parameters:
        image (numpy.ndarray): Input image array of shape (w, h, 3) and dtype ubyte.

    Returns:
        int: Number of unique colors.
    """
    # Reshape the image array to (w * h, 3)
    flattened_image = image.reshape(-1, 3)
    
    # Convert the dtype to int for np.unique() to work correctly
    flattened_image_int = flattened_image.astype(np.int32)
    
    # Compute the unique colors
    unique_colors = np.unique(flattened_image_int, axis=0)
    
    # Return the number of unique colors
    return len(unique_colors)

# Example usage:
# Generate a sample image (replace this with your actual image)
w, h = 10, 10
sample_image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

num_unique_colors = count_unique_colors(sample_image)
print("Number of unique colors in the image:", num_unique_colors)


Number of unique colors in the image: 100


67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [60]:
import numpy as np

# Create a four-dimensional array
array = np.random.randint(0, 10, size=(3, 4, 5, 6))

# Get the sum over the last two axes at once
sum_over_last_two_axes = np.sum(array, axis=(-1, -2))

print("Sum over the last two axes:")
print(sum_over_last_two_axes)


Sum over the last two axes:
[[139 131 138 144]
 [131 136 129 136]
 [122 145 118 137]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices

In [61]:
import numpy as np

def means_of_subsets(D, S):
    """
    Compute the means of subsets of a one-dimensional vector D using subset indices vector S.

    Parameters:
        D (numpy.ndarray): Input one-dimensional vector.
        S (numpy.ndarray): Subset indices vector.

    Returns:
        numpy.ndarray: Means of subsets.
    """
    # Find unique subset indices and their counts
    unique_indices, counts = np.unique(S, return_counts=True)
    
    # Calculate the sums of subsets using np.bincount()
    sums = np.bincount(S, weights=D)
    
    # Calculate the means of subsets
    means = sums / counts
    
    return means

# Example usage:
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 1, 0, 1, 2, 2])

subset_means = means_of_subsets(D, S)
print("Means of subsets:", subset_means)


Means of subsets: [2.  3.  5.5]


69. How to get the diagonal of a dot product? (★★★)

In [62]:
import numpy as np

def diagonal_of_dot_product(A, B):
    """
    Get the diagonal of the dot product of two matrices A and B.

    Parameters:
        A (numpy.ndarray): First matrix.
        B (numpy.ndarray): Second matrix.

    Returns:
        numpy.ndarray: Diagonal of the dot product.
    """
    dot_product = np.einsum("ij,jk->ik", A, B)
    diagonal = np.diagonal(dot_product)
    return diagonal

# Example usage:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

diagonal = diagonal_of_dot_product(A, B)
print("Diagonal of the dot product:", diagonal)


Diagonal of the dot product: [19 50]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)


In [63]:
import numpy as np

# Given vector
original_vector = np.array([1, 2, 3, 4, 5])

# Build a new vector with 3 consecutive zeros interleaved between each value
new_vector = np.zeros(len(original_vector) + 3 * (len(original_vector) - 1))
new_vector[::4] = original_vector

print("Original Vector:", original_vector)
print("New Vector with 3 consecutive zeros interleaved:", new_vector)


Original Vector: [1 2 3 4 5]
New Vector with 3 consecutive zeros interleaved: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [64]:
import numpy as np

# Create a 3D array of dimensions (5, 5, 3)
array_3d = np.random.rand(5, 5, 3)

# Create a 2D array of dimensions (5, 5)
array_2d = np.random.rand(5, 5)

# Multiply the 3D array by the 2D array using broadcasting
result = array_3d * array_2d[:, :, np.newaxis]

print("Result after multiplication:")
print(result)


Result after multiplication:
[[[0.05062884 0.00150156 0.01970094]
  [0.27880837 0.39051906 0.24152435]
  [0.1320167  0.15589843 0.18269673]
  [0.0358377  0.00189634 0.0354536 ]
  [0.03306896 0.17810541 0.23176553]]

 [[0.18212264 0.264969   0.19065403]
  [0.13105696 0.07130895 0.07697236]
  [0.04169869 0.08760894 0.06854111]
  [0.42470759 0.19428702 0.42321007]
  [0.09026536 0.03265643 0.10550361]]

 [[0.46045756 0.27579427 0.14667956]
  [0.21850672 0.25334718 0.19069364]
  [0.06724065 0.10770869 0.04421891]
  [0.83557565 0.86547497 0.55761882]
  [0.00097875 0.00155497 0.0067372 ]]

 [[0.03613706 0.00216783 0.01486961]
  [0.53915261 0.2591494  0.31359038]
  [0.21768664 0.78984944 0.709986  ]
  [0.35730317 0.20843317 0.03810473]
  [0.00407748 0.0050389  0.00706703]]

 [[0.50819757 0.32324839 0.01058012]
  [0.12041923 0.8884236  0.36852305]
  [0.05802543 0.02602913 0.006352  ]
  [0.10834404 0.83887229 0.12819981]
  [0.38896351 0.50832611 0.5322941 ]]]


72. How to swap two rows of an array?

In [65]:
import numpy as np

def swap_rows(array, row1, row2):
    """
    Swap two rows of a NumPy array.

    Parameters:
        array (numpy.ndarray): Input array.
        row1 (int): Index of the first row to swap.
        row2 (int): Index of the second row to swap.

    Returns:
        numpy.ndarray: Array with rows swapped.
    """
    # Copy the array to avoid modifying it in place
    swapped_array = array.copy()
    
    # Swap rows
    swapped_array[[row1, row2]] = swapped_array[[row2, row1]]
    
    return swapped_array

# Example usage:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row1 = 0  # Index of the first row to swap
row2 = 2  # Index of the second row to swap

result = swap_rows(array, row1, row2)
print("Array with rows swapped:")
print(result)


Array with rows swapped:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [66]:
import numpy as np

def extract_line_segments(triplets):
    """
    Extract line segments from a set of triplets describing triangles.

    Parameters:
        triplets (numpy.ndarray): Input array of shape (10, 3, 2) representing 10 triangles.

    Returns:
        set: Set of unique line segments.
    """
    line_segments = set()

    for triangle in triplets:
        # Extract line segments from each triangle
        for i in range(3):
            line_segment = tuple(sorted([tuple(triangle[i]), tuple(triangle[(i + 1) % 3])]))
            line_segments.add(line_segment)

    return line_segments

# Example usage:
triplets = np.random.randint(0, 10, size=(10, 3, 2))

unique_line_segments = extract_line_segments(triplets)
print("Set of unique line segments:")
print(unique_line_segments)


Set of unique line segments:
{((2, 4), (3, 2)), ((8, 6), (8, 7)), ((2, 0), (3, 2)), ((4, 2), (6, 8)), ((0, 3), (9, 0)), ((5, 0), (9, 9)), ((0, 1), (6, 7)), ((6, 6), (6, 8)), ((0, 3), (5, 4)), ((2, 8), (6, 7)), ((6, 3), (9, 9)), ((0, 3), (1, 9)), ((7, 0), (9, 8)), ((8, 7), (8, 7)), ((6, 9), (7, 1)), ((4, 2), (6, 6)), ((5, 3), (6, 9)), ((5, 3), (7, 1)), ((3, 8), (5, 4)), ((6, 6), (9, 1)), ((9, 0), (9, 8)), ((0, 3), (3, 8)), ((0, 1), (2, 8)), ((1, 9), (9, 0)), ((5, 0), (6, 3)), ((5, 3), (6, 6)), ((7, 0), (9, 0)), ((5, 3), (9, 1)), ((2, 0), (2, 4))}


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [68]:
import numpy as np

def array_from_bincount(bincount_array):
    """
    Produce an array A such that np.bincount(A) == bincount_array.

    Parameters:
        bincount_array (numpy.ndarray): Sorted array corresponding to a bincount.

    Returns:
        numpy.ndarray: Array A.
    """
    # Calculate the size of the resulting array A
    size = np.sum(bincount_array)

    # Create an array A by repeating indices according to bin counts
    A = np.repeat(np.arange(len(bincount_array)), bincount_array)

    return A

# Example usage:
C = np.array([1, 2, 0, 1, 0, 1, 0, 0, 2, 1])  # Sorted array corresponding to a bincount

A = array_from_bincount(C)
print("Array A such that np.bincount(A) == C:")
print(A)


Array A such that np.bincount(A) == C:
[0 1 1 3 5 8 8 9]


75. How to compute averages using a sliding window over an array? (★★★)

In [69]:
import numpy as np

def sliding_window_average(array, window_size):
    """
    Compute averages using a sliding window over an array.

    Parameters:
        array (numpy.ndarray): Input array.
        window_size (int): Size of the sliding window.

    Returns:
        numpy.ndarray: Array of averages.
    """
    # Create a sliding window kernel
    kernel = np.ones(window_size) / window_size

    # Compute the sliding window average using convolution
    averages = np.convolve(array, kernel, mode='valid')

    return averages

# Example usage:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3

averages = sliding_window_average(array, window_size)
print("Averages computed using a sliding window of size", window_size, ":", averages)


Averages computed using a sliding window of size 3 : [2. 3. 4. 5. 6. 7. 8.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [70]:
import numpy as np

def build_sliding_window_array(Z, window_size):
    """
    Build a two-dimensional array with a sliding window from a one-dimensional array.

    Parameters:
        Z (numpy.ndarray): Input one-dimensional array.
        window_size (int): Size of the sliding window.

    Returns:
        numpy.ndarray: Two-dimensional array with sliding window.
    """
    # Create an array of indices for the sliding window
    indices = np.arange(window_size)[:, None] + np.arange(len(Z) - window_size + 1)

    # Use the indices to extract the sliding window from the input array
    sliding_window_array = Z[indices]

    return sliding_window_array

# Example usage:
Z = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3

result = build_sliding_window_array(Z, window_size)
print("Two-dimensional array with sliding window:")
print(result)


Two-dimensional array with sliding window:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


77. How to negate a boolean, or to change the sign of a float inplace? 

In [71]:
# Negate a boolean
boolean_value = True
negated_boolean = not boolean_value
print("Negated boolean:", negated_boolean)

# Change the sign of a float inplace
float_value = 3.14
float_value *= -1
print("Float value with changed sign:", float_value)


Negated boolean: False
Float value with changed sign: -3.14


78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

In [ ]:
import numpy as np

def distance_to_line_segment(P0, P1, p):
    """
    Compute the distance from a point p to each line segment defined by points P0 and P1.

    Parameters:
        P0 (numpy.ndarray): Array of shape (n, 2) representing the starting points of line segments.
        P1 (numpy.ndarray): Array of shape (n, 2) representing the ending points of line segments.
        p (numpy.ndarray): Array of shape (2,) representing the point.

    Returns:
        numpy.ndarray: Array of distances from p to each line segment.
    """
    # Direction vector of line segments
    v = P1 - P0

    # Vector from P0 to p
    w = p - P0

    # Dot product of w and v
    dot_product = np.dot(w, v.T)

    # Squared length of line segments
    squared_length = np.sum(v**2, axis=1)

    # Parameter t for projection of p onto line segments
    t = np.clip(dot_product / squared_length, 0, 1)

    # Projection of p onto line segments
    projection = P0 + t[:, np.newaxis] * v

    # Distance from p to projection
    distance = np.linalg.norm(p - projection, axis=1)

    return distance

# Example usage:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
p = np.array([0, 1])

distances = distance_to_line_segment(P0, P1, p)
print("Distances from p to each line segment:", distances)


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 

In [ ]:

import numpy as np

def distance_to_lines(P0, P1, P):
    """
    Compute the distance from each point P[j] to each line segment defined by points P0[i] and P1[i].

    Parameters:
        P0 (numpy.ndarray): Array of shape (n, 2) representing the starting points of line segments.
        P1 (numpy.ndarray): Array of shape (n, 2) representing the ending points of line segments.
        P (numpy.ndarray): Array of shape (m, 2) representing the points.

    Returns:
        numpy.ndarray: Array of shape (m, n) representing the distances from each point to each line segment.
    """
    # Direction vector of line segments
    v = P1 - P0

    # Vector from P0 to each point P[j]
    w = P[:, np.newaxis] - P0

    # Dot product of w and v
    dot_product = np.sum(w[:, :, np.newaxis] * v.T, axis=1)

    # Squared length of line segments
    squared_length = np.sum(v**2, axis=1)

    # Parameter t for projection of each point onto each line segment
    t = np.clip(dot_product / squared_length, 0, 1)

    # Projection of each point onto each line segment
    projection = P0 + t[:, :, np.newaxis] * v

    # Distance from each point to each projection
    distance = np.linalg.norm(P[:, np.newaxis] - projection, axis=2)

    return distance

# Example usage:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [2, 1], [3, 2]])
P = np.array([[0, 1], [1, 2], [2, 3]])

distances = distance_to_lines(P0, P1, P)
print("Distances from each point to each line segment:")
print(distances)


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [74]:
import numpy as np

def extract_subpart(arr, center, shape, fill_value=0):
    """
    Extracts a subpart of an array with a fixed shape centered on a given element.

    Parameters:
    - arr: Input array.
    - center: Center element around which the subpart is extracted.
    - shape: Shape of the subpart.
    - fill_value: Value used for padding when necessary.

    Returns:
    - subpart: Extracted subpart with padding.
    """
    # Calculate the indices for the subpart
    start_idx = np.maximum(center - np.array(shape) // 2, 0)
    end_idx = start_idx + shape
    pad_before = np.maximum(np.array([0, 0]) - start_idx, 0)
    pad_after = np.maximum(end_idx - np.array(arr.shape), 0)

    # Pad the input array
    padded_arr = np.pad(arr, (pad_before, pad_after), mode='constant', constant_values=fill_value)

    # Calculate the slice for the subpart
    slices = tuple(slice(start, end) for start, end in zip(start_idx, end_idx))

    # Extract the subpart
    subpart = padded_arr[slices]

    return subpart

# Example usage:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

center = (1, 2)  # Centered on element 7
shape = (3, 3)
subpart = extract_subpart(arr, center, shape, fill_value=-1)
print(subpart)


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [75]:
import numpy as np

Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Define the size of the sliding window
window_size = 4

# Calculate the number of rows in the resulting array R
num_rows = len(Z) - window_size + 1

# Initialize the array R with zeros
R = np.zeros((num_rows, window_size), dtype=Z.dtype)

# Fill in the values for each row of R
for i in range(num_rows):
    R[i] = Z[i:i+window_size]

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)

In [76]:
import numpy as np

# Define your matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 2


83. How to find the most frequent value in an array?

In [77]:
import numpy as np

# Define your array
arr = np.array([1, 2, 3, 4, 2, 2, 3, 1, 1, 2, 4, 4, 4])

# Find the counts of each unique value
unique_values, counts = np.unique(arr, return_counts=True)

# Find the index of the maximum count
most_frequent_index = np.argmax(counts)

# The most frequent value
most_frequent_value = unique_values[most_frequent_index]

print("Most frequent value:", most_frequent_value)


Most frequent value: 2


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)


In [78]:
import numpy as np

# Generate a random 10x10 matrix
matrix = np.random.randint(0, 10, size=(10, 10))

# Initialize a list to store the 3x3 blocks
blocks = []

# Iterate over each position in the matrix
for i in range(8):  # We go up to 8 because we need a 3x3 block centered at each position
    for j in range(8):
        # Extract the 3x3 block centered at position (i, j)
        block = matrix[i:i+3, j:j+3]
        blocks.append(block)

# Convert the list of blocks to a numpy array
blocks_array = np.array(blocks)

# Print the extracted blocks
for idx, block in enumerate(blocks_array):
    print(f"Block {idx + 1}:")
    print(block)
    print()


Block 1:
[[6 3 3]
 [0 4 8]
 [4 8 3]]

Block 2:
[[3 3 2]
 [4 8 5]
 [8 3 7]]

Block 3:
[[3 2 1]
 [8 5 2]
 [3 7 8]]

Block 4:
[[2 1 0]
 [5 2 4]
 [7 8 7]]

Block 5:
[[1 0 2]
 [2 4 0]
 [8 7 9]]

Block 6:
[[0 2 6]
 [4 0 9]
 [7 9 2]]

Block 7:
[[2 6 1]
 [0 9 0]
 [9 2 2]]

Block 8:
[[6 1 8]
 [9 0 6]
 [2 2 4]]

Block 9:
[[0 4 8]
 [4 8 3]
 [6 0 6]]

Block 10:
[[4 8 5]
 [8 3 7]
 [0 6 2]]

Block 11:
[[8 5 2]
 [3 7 8]
 [6 2 0]]

Block 12:
[[5 2 4]
 [7 8 7]
 [2 0 0]]

Block 13:
[[2 4 0]
 [8 7 9]
 [0 0 3]]

Block 14:
[[4 0 9]
 [7 9 2]
 [0 3 9]]

Block 15:
[[0 9 0]
 [9 2 2]
 [3 9 1]]

Block 16:
[[9 0 6]
 [2 2 4]
 [9 1 8]]

Block 17:
[[4 8 3]
 [6 0 6]
 [6 8 6]]

Block 18:
[[8 3 7]
 [0 6 2]
 [8 6 7]]

Block 19:
[[3 7 8]
 [6 2 0]
 [6 7 6]]

Block 20:
[[7 8 7]
 [2 0 0]
 [7 6 2]]

Block 21:
[[8 7 9]
 [0 0 3]
 [6 2 5]]

Block 22:
[[7 9 2]
 [0 3 9]
 [2 5 1]]

Block 23:
[[9 2 2]
 [3 9 1]
 [5 1 9]]

Block 24:
[[2 2 4]
 [9 1 8]
 [1 9 1]]

Block 25:
[[6 0 6]
 [6 8 6]
 [4 7 9]]

Block 26:
[[0 6 2]
 [8 6 7]
 [7 9 

85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [79]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getitem__(self, indices):
        i, j = indices
        return super().__getitem__((i, j)) if i <= j else super().__getitem__((j, i))

# Create a test array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Create an instance of the SymmetricArray subclass
symmetric_arr = SymmetricArray(arr)

# Test the symmetric property
print("Original array:")
print(arr)
print("Symmetric array:")
print(symmetric_arr)
print("Is symmetric? (Z[i, j] == Z[j, i]):", np.all(symmetric_arr == symmetric_arr.T))


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Symmetric array:
[[1 2 3]
 [2 5 6]
 [3 6 9]]
Is symmetric? (Z[i, j] == Z[j, i]): False


86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [80]:
import numpy as np

def sum_of_matrix_products(matrices, vectors):
    """
    Compute the sum of the products of the p matrices with the corresponding p vectors.

    Parameters:
    - matrices: Array of shape (p, n, n) containing p matrices.
    - vectors: Array of shape (p, n, 1) containing p vectors.

    Returns:
    - result: Array of shape (n, 1) containing the sum of the products.
    """
    # Perform element-wise multiplication of matrices and vectors
    products = matrices @ vectors

    # Sum along the first axis to obtain the result
    result = np.sum(products, axis=0)

    return result

# Example usage:
p = 3
n = 2

# Generate random matrices and vectors
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)

# Compute the sum of matrix products
result = sum_of_matrix_products(matrices, vectors)
print("Result:")
print(result)


Result:
[[1.22625775]
 [1.36297609]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [82]:
import numpy as np

# Create a random 16x16 array
arr = np.random.randint(0, 10, size=(16, 16))

# Reshape the array into a 4D array with shape (4, 4, 4, 4)
blocks = arr.reshape(4, 4, 4, 4)

# Sum along the last two axes to get the block-sum
block_sum = np.sum(blocks, axis=(2, 3))

print("Block sum (shape 4x4):")
print(block_sum)


Block sum (shape 4x4):
[[65 86 49 67]
 [83 96 76 81]
 [64 67 74 76]
 [74 74 93 70]]


88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

def update(frame_num, img, grid, grid_size):
    new_grid = grid.copy()
    for i in range(grid_size):
        for j in range(grid_size):
            # Count live neighbors
            neighbors = np.sum(grid[max(0, i-1):min(grid_size, i+2), max(0, j-1):min(grid_size, j+2)]) - grid[i, j]
            
            # Apply rules
            if grid[i, j] == 1 and (neighbors < 2 or neighbors > 3):
                new_grid[i, j] = 0
            elif grid[i, j] == 0 and neighbors == 3:
                new_grid[i, j] = 1
    
    img.set_data(new_grid)
    grid[:] = new_grid[:]
    return img,

# Set the grid size and the number of frames
grid_size = 50
num_frames = 100

# Create a random initial grid
grid = np.random.choice([0, 1], size=(grid_size, grid_size))

# Set up the animation
fig, ax = plt.subplots()
img = ax.imshow(grid, interpolation='nearest')
ani = animation.FuncAnimation(fig, update, frames=num_frames, fargs=(img, grid, grid_size), interval=50, save_count=50)

plt.show()


89. How to get the n largest values of an array (★★★)

In [84]:
import numpy as np

def n_largest(arr, n):
    """
    Get the n largest values of an array.

    Parameters:
    - arr: Input array.
    - n: Number of largest values to retrieve.

    Returns:
    - largest_values: Array containing the n largest values.
    """
    # Get the indices of the n largest values using partition
    indices = np.argpartition(arr, -n)[-n:]

    # Sort the indices based on the corresponding values
    sorted_indices = indices[np.argsort(arr[indices])]

    # Get the n largest values
    largest_values = arr[sorted_indices]

    return largest_values

# Example usage:
arr = np.array([1, 3, 5, 2, 4, 6])
n = 3
largest_values = n_largest(arr, n)
print("The", n, "largest values are:", largest_values)


The 3 largest values are: [4 5 6]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [85]:
from itertools import product

def cartesian_product(*vectors):
    return list(product(*vectors))

# Example usage:
v1 = [1, 2]
v2 = [3, 4]
v3 = [5, 6]

result = cartesian_product(v1, v2, v3)
print(result)


[(1, 3, 5), (1, 3, 6), (1, 4, 5), (1, 4, 6), (2, 3, 5), (2, 3, 6), (2, 4, 5), (2, 4, 6)]


91. How to create a record array from a regular array? (★★★)

In [86]:
import numpy as np

# Regular array
regular_array = np.array([(1, 2, 3), (4, 5, 6)], dtype=[('a', int), ('b', int), ('c', int)])

# Convert regular array to record array
record_array = regular_array.view(np.recarray)

print(record_array)


[(1, 2, 3) (4, 5, 6)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [89]:
import numpy as np

# Method 1: Using numpy.power()
result1 = np.power(Z, 3)

93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
import numpy as np

# Example arrays A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 2, 4],
              [4, 6, 7],
              [2, 3, 5],
              [8, 9, 1],
              [3, 4, 5]])

B = np.array([[1, 2],
              [3, 4]])

# Convert arrays A and B to sets of tuples for easier comparison
A_set = {tuple(row) for row in A}
B_set = {tuple(row) for row in B}

# Find rows of A that contain elements of each row of B
result_indices = [i for i, row in enumerate(A_set) if all(elem in row for elem in B_set)]

# Get the corresponding rows from A
result_rows = A[result_indices]

print(result_rows)


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)


In [91]:
import numpy as np

# Create a 10x3 matrix
matrix = np.random.randint(0, 5, (10, 3))  # Generating random integers between 0 and 4

# Find rows with unequal values
unequal_rows = matrix[np.any(np.diff(matrix, axis=1) != 0, axis=1)]

print(unequal_rows)


[[0 0 4]
 [4 1 3]
 [3 1 4]
 [3 1 1]
 [4 2 3]
 [4 0 2]
 [3 2 3]
 [3 4 4]]


95. Convert a vector of ints into a matrix binary representation (★★★)

In [92]:
import numpy as np

# Example vector of integers
vector = np.array([5, 10, 3, 7])

# Get the maximum integer value in the vector
max_val = np.max(vector)

# Determine the number of bits required to represent the maximum integer value
num_bits = int(np.ceil(np.log2(max_val + 1)))

# Create a matrix to hold the binary representation
binary_matrix = ((vector[:, None] & (1 << np.arange(num_bits)))) > 0

print(binary_matrix.astype(int))


[[1 0 1 0]
 [0 1 0 1]
 [1 1 0 0]
 [1 1 1 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★)

In [93]:
import numpy as np

# Example two-dimensional array
array_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [1, 2, 3],
                      [7, 8, 9],
                      [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print(unique_rows)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
inner_product = np.einsum('i,i->', A, B)
outer_product = np.einsum('i,j->ij', A, B)
sum_result = np.einsum('i,i->i', A, B)
elementwise_multiplication = np.einsum('i,i->i', A, B)


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
import numpy as np

def sample_path(X, Y, num_samples):
    # Compute the total length of the path
    path_length = np.sum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
    
    # Compute the step size for equidistant samples
    step_size = path_length / (num_samples - 1)
    
    # Interpolate along the path to get equidistant samples
    t = np.linspace(0, 1, len(X))
    interp_func = np.interp(np.arange(0, path_length, step_size), np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2)), t)
    
    # Interpolate X and Y coordinates using the interpolation function
    sampled_X = np.interp(interp_func, t, X)
    sampled_Y = np.interp(interp_func, t, Y)
    
    return sampled_X, sampled_Y

# Example vectors (X, Y)
X = np.array([0, 1, 3, 6, 9])
Y = np.array([0, 2, 4, 7, 10])

# Number of equidistant samples
num_samples = 10

# Sample the path
sampled_X, sampled_Y = sample_path(X, Y, num_samples)

print("Sampled X:", sampled_X)
print("Sampled Y:", sampled_Y)


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [96]:
import numpy as np

def is_multinomial_row(row, n):
    # Check if the row contains only integers
    if not np.all(np.equal(np.mod(row, 1), 0)):
        return False
    
    # Check if the sum of the row equals n
    if np.sum(row) != n:
        return False
    
    return True

def select_multinomial_rows(X, n):
    selected_rows = []
    
    for row in X:
        if is_multinomial_row(row, n):
            selected_rows.append(row)
    
    return np.array(selected_rows)

# Example 2D array X and integer n
X = np.array([[1, 2, 3],
              [4, 5, 1],
              [0, 3, 2],
              [2, 2, 6]])

n = 6

# Select rows from X which can be interpreted as draws from a multinomial distribution with n degrees
selected_rows = select_multinomial_rows(X, n)

print("Selected rows:")
print(selected_rows)


Selected rows:
[[1 2 3]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [98]:
import numpy as np

def bootstrap_confidence_interval(X, N, alpha=0.05):
    means = []
    
    # Perform bootstrap resampling
    for _ in range(N):
        # Resample with replacement
        resampled_X = np.random.choice(X, size=len(X), replace=True)
        # Compute mean of resampled data
        mean = np.mean(resampled_X)
        means.append(mean)
    
    # Compute confidence intervals
    lower_percentile = 100 * (alpha / 2)
    upper_percentile = 100 * (1 - alpha / 2)
    lower_bound = np.percentile(means, lower_percentile)
    upper_bound = np.percentile(means, upper_percentile)
    
    return lower_bound, upper_bound

# Example 1D array X
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Number of bootstrap resamples
N = 1000

# Compute bootstrapped 95% confidence intervals for the mean of X
lower_bound, upper_bound = bootstrap_confidence_interval(X, N)

print("Bootstrapped 95% confidence interval for the mean of X:", (lower_bound, upper_bound))


Bootstrapped 95% confidence interval for the mean of X: (3.7975, 7.3)
